apiVersion: v1
kind: Service
metadata:
  name: tags-service
  namespace: lab2-microservices
spec:
  type: ClusterIP
  selector:
    app: tags-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
