apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-service
  namespace: lab2-microservices
  labels:
    app: router-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router-service
  template:
    metadata:
      labels:
        app: router-service
    spec:
      containers:
        - name: router-service
          image: lilarin/router-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"
