apiVersion: v1
kind: Service
metadata:
  name: router-service
  namespace: lab2-microservices
spec:
  type: ClusterIP
  selector:
    app: router-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
