apiVersion: v1
kind: Service
metadata:
  name: shard-service
  namespace: lab2-microservices
spec:
  selector:
    app: shard-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
