apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: lab2-microservices
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - 'alertmanager-service:9093'

    rule_files:
      - /etc/prometheus/alert_rules.yml

    scrape_configs:
      - job_name: 'lab3-microservices'
        static_configs:
          - targets: [ 'api-gateway:80' ]
            labels:
              service: 'gateway'
          
          - targets: [ 'router-service:8000' ]
            labels:
              service: 'router'
          
          - targets: [ 'shard-service:8000' ]
            labels:
              service: 'shard'

  alert_rules.yml: |
    groups:
      - name: microservices_alerts
        rules:
          - alert: InstanceDown
            expr: up == 0
            for: 10s
            labels:
              severity: critical
            annotations:
              summary: "Instance {{ $labels.instance }} down"
              description: "{{ $labels.instance }} of job {{ $labels.job }} has been down."

          - alert: HighErrorRate
            expr: rate(http_requests_total{status=~"5.."}[1m]) / rate(http_requests_total[1m]) > 0.05
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "High error rate on {{ $labels.instance }}"

          - alert: HighLatency
            expr: histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[1m])) > 1
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "High P99 latency on {{ $labels.instance }}"
          
          - alert: HighReplicationLag
            expr: shard_replication_lag_seconds > 5
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "High replication lag on {{ $labels.instance }}"