apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secrets
  namespace: lab2-microservices
type: Opaque
stringData:
  JWT_SECRET: "tBxXjOZRs7jqcruLUhRQ8n8/epT759ZndrcZVJJBiGbeFvzTr2cJyA/g1lCQVkni55O2/WNoW0ohXRZGZ4JyXg=="
  SUPABASE_URL: "https://yjumgvinrznejlkotlkh.supabase.co"
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqdW1ndmlucnpuZWpsa290bGtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0MjUwNjQsImV4cCI6MjA1MjAwMTA2NH0.CyksKQmvs8OjwHpVkIvOTYVGD-fgM6HjtzgdneiJO7c"
